<?php

namespace Tests\Feature;

use App\Role;
use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class UserRegistrationTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub

        factory(Role::class)->create([
            'code' => 'general'
        ]);
    }

    /**
     * @test
     */
    public function create_new_user() {
        $data = [
            'name'                  => "Xavier Au",
            'email'                 => "xavier.au@gmail.com",
            'employee_id'           => "123456",
            'password'              => "password",
            'password_confirmation' => "password",
        ];
        $this->post("/register", $data);
        $record = [
            'name'        => "Xavier Au",
            'email'       => "xavier.au@gmail.com",
            'employee_id' => "123456",
        ];
        $this->assertDatabaseHas('users', $record);
    }

    /**
     * @test
     */
    public function duplicate_employee_id()  {

        $data = [
            'name'                  => "Xavier Au",
            'email'                 => "xavier.au+for_unit_testing@gmail.com",
            'employee_id'           => "123456_unitTesting",
            'password'              => "password",
            'password_confirmation' => "password",
        ];

        factory(User::class)->create([
            'employee_id'           => "123456_unitTesting"
        ]);
        $response = $this->post("/register", $data);

        $response->assertSessionHasErrors('employee_id');
    }
}
